version: "2.0"

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    ports:
      - "127.0.0.1:5300:5300"
      - "127.0.0.1:5300:5300/udp"
    command: python src/dns-server.py

  test-server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    ports:
      - "127.0.0.1:5300:5300"
      - "127.0.0.1:5300:5300/udp"
    command: python src/dns-server.py --test
    networks:
      webapi:
  test-dns:
    env_file:
      - .env
    image: praqma/network-multitool
    working_dir: /mnt
    volumes:
      - .:/mnt
    command: >
      sh -c "./test/test_wait-for-server.sh test-server:5300 &&
              bash test/test_dns-server.sh"
    networks:
      webapi:

networks:
  webapi:
    driver: bridge